apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- local/

# NOTE
# ----
# 1. Provisioning local storage PVs. The volume provisioning process
# is machine-dependent and manual for now. But you can use the config
# for the volumes on the two machines we've built (devm and tv-teadal)
# as a starting point. See the Kustomization in each of those to get
# an idea of what to do.
# 2. Argo CD pipeline. This Kustomization isn't meant to be included
# in the Argo CD pipeline, but it's rather here as an example of how
# to provision local storage.
