apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - keycloak.yaml
# - minio-data-1.yaml
# - minio-data-2.yaml
# - minio-data-3.yaml
# - minio-data-4.yaml
# - postgres.yaml
- local/
