apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: directpv-min-io
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 500Mi
