apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.1.2
        args:
        - start
        env:
        # Use HTTP (we'll switch to HTTPs later on for pilot deployments)
        # and build URLs of depending on host and port found in the request.
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HTTP_RELATIVE_PATH
          value: /keycloak/
        - name: KC_HOSTNAME_STRICT
          value: "false"

        # NOTE this initial admin can only be used on first boot.
        # In fact, Keycloak will create it in its DB only if it isn't
        # there already. So the second time this pod restarts the user
        # will be there and changing the password through the below env
        # var will have no effect---you'll have to log onto Keycloak to
        # change it. This is why we're not asking Reloader to monitor
        # changes to this pod's linked secret.
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-builtin-admin
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-builtin-admin
              key: password
        ports:
        - name: http
          containerPort: 8080
        # - name: https
        #   containerPort: 8443
        readinessProbe:
          httpGet:
            path: /keycloak/realms/master
            port: 8080
        volumeMounts:
        - name: h2-volume
          mountPath: /opt/keycloak/data/h2/
      volumes:
      - name: h2-volume
        persistentVolumeClaim:
          claimName: keycloak-pvc
