schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.81.0"
    hash = "sha256-N4A6IPDmRhkOAXJCWW8UODt0otEdIw0MOvdIK5kdLYk="
  [mod."github.com/Azure/go-autorest"]
    version = "v14.2.0+incompatible"
    hash = "sha256-dvWOcudtx0NP6U2RDt40hwtELFRdYdLEklRWYterRN0="
  [mod."github.com/Azure/go-autorest/autorest"]
    version = "v0.11.18"
    hash = "sha256-j6IViAvhZ5r06n1qpGVy4aUF/pEYhQknkTQJa1qFtBI="
  [mod."github.com/Azure/go-autorest/autorest/adal"]
    version = "v0.9.13"
    hash = "sha256-hPrY0ZmA/x6NDCViEdlg44nPjQirxA4ct5SzUMp43NY="
  [mod."github.com/Azure/go-autorest/autorest/date"]
    version = "v0.3.0"
    hash = "sha256-PWFHUZ9jMJ6gkMCnRpR89s/aI3YdtzskIePj8Ulu4dc="
  [mod."github.com/Azure/go-autorest/logger"]
    version = "v0.2.1"
    hash = "sha256-xGqpcF7fL1MQCN4xXTHpAFDzEA5f4p6kdb9yV1+uB4k="
  [mod."github.com/Azure/go-autorest/tracing"]
    version = "v0.6.0"
    hash = "sha256-CcLYoOyRcMo4aRRYN+TBbaHtJqDra4e0qo3cmGZIB74="
  [mod."github.com/PuerkitoBio/purell"]
    version = "v1.1.1"
    hash = "sha256-Hjf8ZNNdwcRd50A9QNrcCj17gu/6f1iKzVTVrrMrojA="
  [mod."github.com/PuerkitoBio/urlesc"]
    version = "v0.0.0-20170810143723-de5bf2ad4578"
    hash = "sha256-nL0/0QM0Pec83vBlwXvQ8g5SvvZnCQgzD1apxfHNGlg="
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20190424111038-f61b66f89f4a"
    hash = "sha256-pcrINvdGpQExaSQv1j19L0NLWcvZL8jXQMsvMlVq8ss="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.2"
    hash = "sha256-YV9SmXDtmmgQylQUfrUgQLAPfqYexcHxegMBT+IX9qM="
  [mod."github.com/container-storage-interface/spec"]
    version = "v1.3.0"
    hash = "sha256-gCOptvLdZXuwfCvWT41ZntJNYxG46O68HneOzy0IdR4="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/docker/distribution"]
    version = "v2.8.1+incompatible"
    hash = "sha256-xB+w8Uaz8T6jb2LOJU5XAoMHFg/YQd3MfDFOUNKlMxE="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.8.0"
    hash = "sha256-VIy44CDcwVVHsUobY/LxdN/JcV5RcZS74s2q9xIxkSw="
  [mod."github.com/evanphx/json-patch"]
    version = "v4.12.0+incompatible"
    hash = "sha256-rUOokb3XW30ftpHp0fsF2WiJln1S0FSt2El7fTHq3CM="
  [mod."github.com/fatih/color"]
    version = "v1.12.0"
    hash = "sha256-L0KGBvYZEFQ4vuWhIe/2E2rUERL4bsiFt+hHleAm2WQ="
  [mod."github.com/form3tech-oss/jwt-go"]
    version = "v3.2.3+incompatible"
    hash = "sha256-2YU7EMWUrpWepYr0WXbiZjt7t4dhNeNq+e/IRQdNAG0="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.0"
    hash = "sha256-7WHqYgAU02S3HyhnJCTT/M1iM+Cy8QEBbcyYGna36nU="
  [mod."github.com/go-openapi/errors"]
    version = "v0.19.2"
    hash = "sha256-Z1ZzcvnHbVgY2c20b5Dn5SRe4b6ZEA149JEoOzQYxr0="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.5"
    hash = "sha256-rLyvUdTMeQGeWiVsz2ZeyyFjHomeqd0x+ZR77mxi8Ss="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.19.5"
    hash = "sha256-EMbFFOrhvKFVmJ2vierWGCmDy1Vl08HBgUBd9xw2cD8="
  [mod."github.com/go-openapi/strfmt"]
    version = "v0.19.3"
    hash = "sha256-HMKD3i2QrR3IXWUn4+Nqpk8WQZ+WUh1WZq3IVGBaIMg="
  [mod."github.com/go-openapi/swag"]
    version = "v0.19.14"
    hash = "sha256-MRuOz461M5BHBAGYJdhBA8vP682EocgvgGQxpXxhJbo="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.0"
    hash = "sha256-26RlTEcAkbewMUtmirKrDGQ1WJlNousp69v7HMopYnI="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/gnostic"]
    version = "v0.5.7-v3refs"
    hash = "sha256-faR3RiaCBLgZsG1H5KRimlyOu4Grv1ENlYn3f7OAzhU="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.6"
    hash = "sha256-OlzzRmcIdX45NA5h/C90NfJ/th0LB+tMHT6WzdQFK1M="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/uuid"]
    version = "v1.1.2"
    hash = "sha256-DXttjObhEiMn5/OH+mYkJU6u03Gwsx5t08lTsIFyd+U="
  [mod."github.com/gopherjs/gopherjs"]
    version = "v0.0.0-20190328170749-bb2674552d8f"
    hash = "sha256-YQsg2nfxyI9xsQPH4v3dxSDJJ12TpNfea7y72MQNtXI="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.7"
    hash = "sha256-yNXqoLl+47jqY8Soqm8LNqZy9klNwkxDdB5wcqQEORY="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/jedib0t/go-pretty"]
    version = "v4.3.0+incompatible"
    hash = "sha256-YwF9DeP4rzOMiiJL/hujO/gsUkjoKFwjF0OeG3Awmog="
  [mod."github.com/jedib0t/go-pretty/v6"]
    version = "v6.0.5"
    hash = "sha256-grg9UJZIfPQVyAQSnlCAXe7GQCEJVjbG1+IGtKekagc="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.0.4"
    hash = "sha256-3Gwt/jjUixXAm/RvOVwxn7c3VuDIKGgiFt3ORQzKOa8="
  [mod."github.com/kubernetes-csi/csi-lib-utils"]
    version = "v0.7.0"
    hash = "sha256-2ZpIrT0km0PUGryDxrO2Nll6F3M+c/B+MoYvgnzrgtE="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.5"
    hash = "sha256-dnVYJAEVGfVthpfcW3G1tsEZl8APaFgXXQ4MBqd9imw="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.6"
    hash = "sha256-lObieB06Ep7xL3Bbc1sxWpAeqH9VH2LXsPIc9uueuXs="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.8"
    hash = "sha256-TBXc2n5tRebabjt0HipS8wCdRml0kM0JjpppUbdx1XQ="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.13"
    hash = "sha256-8dof20YZW6ado90UG9kDrjCAnlWyRSOE3Jw4K3WEZyQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.9"
    hash = "sha256-dK/kIPe1tcxEubwI4CWfov/HWRBgD/fqlPC3d5i30CY="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.2-0.20181231171920-c182affec369"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mb0/glob"]
    version = "v0.0.0-20160210091149-1eb79d2de6c4"
    hash = "sha256-tV6raCAq3lBVHMr+/X6kMwxqd68gysAeUV8iqz54q1s="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.0"
    hash = "sha256-oEo/BoMqSLdwSjrhHTiFjl5Om4MVLNQXDJINk6Z110Y="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.4.1"
    hash = "sha256-+xC5Th05FPFaWNMdAuX9YCwZpj0X1SD2t22a1VTkKNU="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.3"
    hash = "sha256-2bTSt1K6eDceRIIpNfv3HepMqoCrOIC7Ufnrj2x4yJg="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.12.2"
    hash = "sha256-d8xHyML/FImuPmFOy7UGW/y85NPLzJYL6IFhR3s7XzE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.32.1"
    hash = "sha256-LdgJBz4EcjrBaZVr2CjDjM0hTwRFQIJE2yACEG631bQ="
  [mod."github.com/prometheus/procfs"]
    version = "v0.7.3"
    hash = "sha256-ik0WpnpSjMwifPYfQTfu/eb5ilNj+eLJF0d5Dftp8A8="
  [mod."github.com/smartystreets/assertions"]
    version = "v1.1.1"
    hash = "sha256-X2IxtzKiPKHLlYClfDJUmdPJk7gIaMqhtFKMCYNKumk="
  [mod."github.com/spf13/afero"]
    version = "v1.6.0"
    hash = "sha256-ZzzshKZRvdo9JlPlhJ7VVymGfRSvP8XIY7fF2D24KHo="
  [mod."github.com/spf13/cast"]
    version = "v1.3.1"
    hash = "sha256-wT6IRl4ZFvzeyLlv7l/GJt39shnRRYHzxyDTh9AhaFE="
  [mod."github.com/spf13/cobra"]
    version = "v1.4.0"
    hash = "sha256-I6j9sD61Ztcc2W/WGeWo3ggYtnGTxNxZ2EFPdtO0UEY="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.8.1"
    hash = "sha256-BkMQy6r+isc+cRZSDGTftApMyGXxG1UzCPsWQFPbmkk="
  [mod."github.com/subosito/gotenv"]
    version = "v1.2.0"
    hash = "sha256-RUsfBl9xvHk8H6SPwiLi/BpHjkyO/YLvlFmRfGRIW1U="
  [mod."go.mongodb.org/mongo-driver"]
    version = "v1.9.1"
    hash = "sha256-clxW2SsQhUxY9L6mdMYJfGUb7HkMkelezLMuCBi44us="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."go.uber.org/multierr"]
    version = "v1.6.0"
    hash = "sha256-X+l7OPAkMhpw+5VvFWuQ/DfTCSjQH/8VvSoQrb44CEU="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220214200702-86341886e292"
    hash = "sha256-Mg/1EHDCtRLt1hyPp836ONo3p1UGtne6nxKPY0TdX6I="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220722155237-a158d28d115b"
    hash = "sha256-TccMT2GgC1qKp8Yxk1zShJVvr29GemCqKSNJeYkjLo4="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20211104180415-d3ed0bb246c8"
    hash = "sha256-mE99ygMLxlbLazt3kqIteXAFnS05EHVE14CyOFPfk+8="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220722155257-8c9f86f7a55f"
    hash = "sha256-mXgFTb2vfUEjTPA6PX7CZTvKGJWaxoU2QplyI1GjC+w="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210927222741-03fcf44c2211"
    hash = "sha256-DsX2xay7Y/0/bikp4vU8ArF0B6KHyqEc37PwgvmjhSs="
  [mod."golang.org/x/text"]
    version = "v0.3.8"
    hash = "sha256-KKHU0OMfT4oxTIzIVqan8MY8wNvgBW00s24hF+kWbMA="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20220210224613-90d013bbcef8"
    hash = "sha256-pg5k2aqln5KoTOK/vya61T7DALmcs0CFVH9MPUj62v0="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20220107163113-42d7afdf6368"
    hash = "sha256-BbzLhQXgyrknnuWshF0r/PLIy2LOy6669vEPiMUXDnY="
  [mod."google.golang.org/grpc"]
    version = "v1.40.0"
    hash = "sha256-8O5svL9J3wgPuwQrCl59ZpNlmasR6bP1PO1i3QC+5mw="
  [mod."google.golang.org/protobuf"]
    version = "v1.27.1"
    hash = "sha256-klLGFG4InPHIBDgisRph7H/02D5rBVx0ho9rZCRyLbk="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20200902074654-038fdea0a05b"
    hash = "sha256-pFro5uj8Nxt1NLLVSSHowWEXFMLv/3xPy/S5FcC/Exg="
  [mod."gopkg.in/freddierice/go-losetup.v1"]
    version = "v1.0.0-20170407175016-fc9adea44124"
    hash = "sha256-0d2g7spQF161Nt+Tkd4hwc3bup8gXxex3EaytDH6QUE="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/ini.v1"]
    version = "v1.62.0"
    hash = "sha256-u9T6wgmbmG+hw8qiGLkWdxo9DgdrChFpuVpR53HzqbY="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0"
    hash = "sha256-XWfvIV7+KXlZV4sBZd0srGeuQonS9cTYptCc6NcgVvc="
  [mod."k8s.io/api"]
    version = "v0.24.3"
    hash = "sha256-9NZFjbsTcWpF3pVArjoA/rWNWpmBDiVRQ1ZSn8fzK0M="
  [mod."k8s.io/apiextensions-apiserver"]
    version = "v0.24.3"
    hash = "sha256-l1rmew7daUjFD+4YyoZQ3H9BoMB1lRgZ5YtXN7H7RQ4="
  [mod."k8s.io/apimachinery"]
    version = "v0.24.3"
    hash = "sha256-L2OtNFwH3jk4JEAicwLK+HAIWGGII/JgpXX2njDYPBQ="
  [mod."k8s.io/client-go"]
    version = "v0.24.3"
    hash = "sha256-9WSXB1w4xonGvtLfIw+6kQRwXvCqjwG1G1JX/Dab0SQ="
  [mod."k8s.io/klog/v2"]
    version = "v2.60.1"
    hash = "sha256-dygtN0ILRAZZqgC0JdjE/g5PMX00wx0bFneUns5jDC0="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20220627174259-011e075b9cb8"
    hash = "sha256-xnBxqV964p7h38yzUcMADRz9K+wwPQIIZGZHwSYWIzU="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20220210201930-3a6ce19ff2f9"
    hash = "sha256-febG3/tAx/zu7mKbEA2/FOKRXtQsFmPJZaWTvIyFIBU="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20211208200746-9f7c6b3444d2"
    hash = "sha256-b3BskkIoyuLVp8ZNemQRjc490HD/repEQEN0nZe+RR0="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.2.1"
    hash = "sha256-OIeAxdBo7ws4UAqHeep/h3wYrjHtMNITqKlY9d9qRCo="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.2.0"
    hash = "sha256-HHqIfaFuKGalif3bP2CcHm8MT8Ily1kJQL9Q8Kz2WHA="
