apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - base.yaml
# - microk8s.yaml


# NOTE
# ----
# 1. Installation. To install DirectPV you'll have to choose one of
# the two files above depending on whether you're installing on a
# standard K8s cluster (use `base.yaml` in this case) or MicroK8s.
# Notice DirectPV only supports x86-64/amd64 architectures, so don't
# try installing on Aarch64/ARM64. See:
# - https://github.com/c0c0n3/teadal.proto/issues/8
#
# 2. Operation. Use the Nix-bundled plugin to manage drives, e.g.
#
#    $ cd nix && nix shell
#    $ kubectl directpv discover
#    $ kubectl directpv init --dangerous drives.yaml
#
# 3. Manifest generation. We generated the initial base YAML file by
# running:
#
#     $ cd nix && nix shell
#     $ kubectl directpv install -o yaml > base.yaml
#
# whereas we had to do this for the MicroK8s manifests
#
#     $ cd nix && nix shell
#     $ export KUBELET_DIR_PATH=/var/snap/microk8s/common/var/lib/kubelet
#     $ kubectl directpv install -o yaml > microk8s.yaml
#
# See:
# - https://github.com/minio/directpv/issues/816#issuecomment-1637071486
#
# 4. Testing. Read the README in the test dir---pun intended :-)
