apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base.yaml


# NOTE
# ----
# 1. Direct PV. We generated the initial YAML file by running:
#
# $ cd nix && nix shell
# $ kubectl directpv install -o yaml > base.yaml
#
# Notice our version of Direct PV (4.0.6) can only generate manifests
# for x86_84/amd64. This is b/c they pull specific images for those
# architectures. The `base.arm64.yaml` manifest fixes that by replacing
# x86_84/amd64 images w/ arm64 ones. Diff the two files.
