#
# Plain K8s Secret template for the Keycloak built-in admin user.
#
# WARNING. **Never** commit this file to the repo with an actual
# password in it. After editing this file, just ask git to ditch
# the local changes.
#
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-builtin-admin
  namespace: default
type: Opaque
stringData:
  username: admin
  password: abc123
