#
# Plain K8s Secret template for MinIO secrets.
#
# WARNING. **Never** commit this file to the repo with an actual
# password in it. After editing this file, just ask git to ditch
# the local changes.
#
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: default
type: Opaque
stringData:
  minio.access-key: minio
  minio.secret-key: abc123..
