apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: teadal
  namespace: minio-operator
scheduler:
  name: ""
spec:
  certConfig:
    commonName: '*.teadal-hl.minio-operator.svc.cluster.local'
    dnsNames:
    - teadal-teadal-0.teadal-hl.minio-operator.svc.cluster.local
    organizationName:
    - system:nodes
  configuration:
    name: teadal-env-configuration
  exposeServices:
    minio: true
  image: minio/minio:RELEASE.2023-06-23T20-26-00Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - teadal
          topologyKey: kubernetes.io/hostname
    name: teadal
    resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-storage
      status: {}
    volumesPerServer: 1
  requestAutoCert: false
  serviceAccountName: teadal-sa
  users:
  - name: teadal-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}

---
apiVersion: v1
data:
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0iTFRYRzVDVlkwTVhMRTBXTzc1UTYiCmV4cG9ydCBNSU5JT19ST09UX1BBU1NXT1JEPSJJS3hwczlHVGlQR0JaYUs2QlJtZUY0MzRsR1pDTngwWEczc2E0UExFIgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: teadal-env-configuration
  namespace: minio-operator

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: S04zMzVHRjVKMEdBMTA0SE1INFM=
  CONSOLE_SECRET_KEY: UmpMSlNFSHdQbWdCdGtEYnVxb0RpUTlFNDRVS2w2RjROdE9VMWpwTQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: teadal-user-1
  namespace: minio-operator

